import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { Button } from "@/components/Button";

type TPost = {
  id: number;
  title: string;
  content: string;
};

const data: TPost = { id: 1, title: "title1", content: "content1" };

export default function CSR() {
  const [post, setPost] = useState<TPost | null>(null);
  const [isLoading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    setPost(data);
    setLoading(false);
  });

  if (isLoading) return <p>Loading...</p>;
  if (!post) return <p>No profile data</p>;

  return (
    <>
      <Head>
        <title>CSR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div>Static Generation With Data depends on paths</div>
        </div>
        <div>{post.title}</div>
        <div>{post.content}</div>
        <Button />
      </main>
    </>
  );
}
