import Head from "next/head";
import styles from "@/styles/Home.module.scss";

export default function StaticGenerationNoData() {
  return (
    <>
      <Head>
        <title>SSG - no data</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div>Static Generation With No Data</div>
        </div>
      </main>
    </>
  );
}
